# Config file for the `gpu-usage-waybar` tool
# [general]
# Interval to update the GPU usage in milliseconds
# interval = 1000

# [text]
# format = "{gpu_utilization}%|{mem_utilization}%"

# [tooltip]
# format = """GPU: {gpu_utilization}%
# MEM USED: {mem_used:MiB.0}/{mem_total:MiB.0} MiB ({mem_utilization}%)
# MEM R/W: {mem_rw}%
# DEC: {decoder_utilization}%
# ENC: {encoder_utilization}%
# TEMP: {temperature:c.0}Â°C
# POWER: {power:w.0}W
# PSTATE: {p_state}
# PLEVEL: {p_level}
# FAN SPEED: {fan_speed}%
# TX: {tx:MiB.0} MiB/s
# RX: {rx:MiB.0} MiB/s"""
